project:
  type: website
  output-dir: docs

website:
  title: Georgi Baklicharov
  navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: About
      - presentations.qmd
      - teaching.qmd
  page-footer: "&#169; Georgi Baklicharov, 2024"
      

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: false
    page-layout: full

editor: visual

